# tasks file for loadbalancer
- name: "Install package"
  package:
          name: "haproxy"
          state: present
- name: "Copy Template file Name haproxy.cfg"
  template:
          src: "haproxy.cfg"
          dest: "/etc/haproxy/haproxy.cfg"
- name: "restart haproxy"
  service:
     name: "haproxy"
     state: "started"



